export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS"
export const GET_LOCATIONS_STARTED = "GET_LOCATIONS_STARTED"
export const GET_LOCATIONS_FAILURE = "GET_LOCATIONS_FAILURE"

export const GET_PERSONAGE_TYPES_SUCCESS = "GET_PERSONAGE_TYPES_SUCCESS"
export const GET_PERSONAGE_TYPES_STARTED = "GET_PERSONAGE_TYPES_STARTED"
export const GET_PERSONAGE_TYPES_FAILURE = "GET_PERSONAGE_TYPES_FAILURE"
